INSERT INTO docente VALUES('00001', 'Luke', 'Skywalker', 'INFORMATICA;CHIMICA;ANALISI');
INSERT INTO docente VALUES('00002', 'Jon', 'Snow', 'INFORMATICA;ANALISI');
INSERT INTO docente VALUES('00003', 'Francesco', 'Totti', 'STATISTICA;FISICA;CHIMICA;DIRITTO');
